spring:
  datasource:
  #  driver-class-name: org.h2.Driver
  #  url: jdbc:h2:mem:./library
  #  platform: h2
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_jobs
    username: root
    password:
  jpa.hibernate:
    ddl-auto: validate
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  batch:
    job:
      enabled: false
      names: 311-data


logging.level:
  org.springframework.boot.web: WARN
  org.springframework.boot.context: WARN
  org.springframework.web: WARN
  org.springframework.orm: WARN
  org.springframework.core: WARN
  org.springframework.jmx: WARN
  org.hibernate: WARN
  org.apache.catalina: WARN

server:
  port: 9000

flyway:
  locations: classpath:/db/migration
  enabled: true

nyc.data:
  url: https://data.cityofnewyork.us/resource/fhrw-4uyv.json
  appToken: yourTokenHereOrInEnv
  limit: 500
