spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:./library
    platform: h2
  jpa.hibernate.ddl-auto: none

flyway.locations: classpath:/db/migration

logging.level:
  org.springframework.boot.web: WARN
  org.springframework.boot.context: WARN
  org.springframework.web: WARN
  org.springframework.orm: WARN
  org.springframework.core: WARN
  org.springframework.jmx: WARN
  org.hibernate: WARN
  org.apache.catalina: WARN

server:
  port: 9000

