CREATE TABLE service_requests (
  uniqueKey       BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  createdDate     TIMESTAMP,
  closedDate      TIMESTAMP,
  addressType     VARCHAR(50) NOT NULL,
  agencyName      VARCHAR(100),
  agency          VARCHAR(50) NOT NULL,
  complaintType   VARCHAR(100),
  descriptor      VARCHAR(500),
  locationType    VARCHAR(100),
  incidentType    VARCHAR(100),
  incidentZip     VARCHAR(8),
  incidentAddress VARCHAR(100),
  streetName      VARCHAR(100),
  crossStreet1 VARCHAR(100),
  crossStreet2 VARCHAR(100),
  intersectionStreet1 VARCHAR(100),
  intersectionStreet2 VARCHAR(100),
  city VARCHAR(50),
  landmark VARCHAR(100),
  facilityType VARCHAR(100),
  status VARCHAR(25)
);