server.port: 8081

logging:
  level:
    root: WARN

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_jobs
    username: root
    password: root

nyc.data:
  appToken: token
  limit: 500
  url: https://data.cityofnewyork.us/resource/fhrw-4uyv.json